---
title: "Cleaning Yarn"
format: html
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(dplyr)
```

```{r}
yarn <- read_csv("~/Desktop/16/CS200B/project/yarn.csv")
fibers <- read_csv("~/Desktop/16/CS200B/project/yarn_fibers.csv")
```

```{r}
final_yarn <- yarn |>
  left_join(fibers) |>
  filter(discontinued == "FALSE", 
         percentage == 100, 
         !is.na(rating_average), 
         !is.na(yardage), 
         rating_count >= 1,
         !is.na(yarn_weight_name)) |>
  select(-c("yarn_weight_crochet_gauge", "thread_size", "wpi", "max_gauge")) |>
  mutate(fiber_type_name = fct_recode(fiber_type_name, Wool = "Merino"), 
         yarn_weight_name = fct_recode(yarn_weight_name, DK = "DK / Sport"), 
         yarn_weight_name = fct_recode(yarn_weight_name, Aran = "Aran / Worsted"))

final_yarn |>
  count(rating_average)
```

```{r}
#final_yarn <- final_yarn |> 
#  select(-c("discontinued", "percentage"))

#write_csv(final_yarn, "~/Desktop/16/CS200B/project/final_yarn.csv")
```



